name: Test Coverage

on: [push]

jobs:  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    = name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        npm install -g codecov 
        npm i -D nyc
      env:
        CI: true

    - name: npm test-coverage
      run: |
        npm run test-coverage && npm run codecov
      env:
        CI: true